# Generated by Django 3.1.7 on 2021-03-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_palace_words_to_remember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palace',
            name='words_to_remember',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
