# Generated by Django 3.1.7 on 2021-03-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210308_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palace',
            name='words_to_remember',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
