# Generated by Django 3.1.7 on 2021-03-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_palace_trigger_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palace',
            name='trigger_words',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
