# Generated by Django 3.1.7 on 2021-03-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210308_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='palace',
            name='first_letter_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='palace',
            name='previous_word_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='palace',
            name='phonetic_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='palace',
            name='second_letter_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='palace',
            name='theme',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='palace',
            name='trigger_words',
            field=models.CharField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='palace',
            name='version',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='palace',
            name='words_to_remember',
            field=models.CharField(max_length=50000),
        ),
    ]
